# Generated by Django 3.2.6 on 2021-08-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=70, unique=True, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=5, null=True, verbose_name='Estado')),
                ('country', models.CharField(max_length=3, verbose_name='País')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Localizaçao',
                'verbose_name_plural': 'Localizações',
                'unique_together': {('city', 'longitude', 'latitude')},
            },
        ),
    ]
