# Generated by Django 3.2.6 on 2021-08-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_location_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=3, null=True, verbose_name='País'),
        ),
    ]
